name: caching_deeprl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - tqdm
  - pip
  - pip:
    - gymnasium
    - stable-baselines3
    - tensorboard